# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/




en:
  languageCode: en
  contentDir: content/en
  weight: 1
  title: "My Portfolio"
  params:
    description: "English version of my portfolio"

ko:
  languageCode: ko
  contentDir: content/ko
  weight: 2
  title: "나의 포트폴리오"
  params:
    description: "한국어 버전 포트폴리오"

# Default language
defaultContentLanguage: ko
defaultContentLanguageInSubdir: false

#en:
  #languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en
  
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
