# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Home
  #  url: /
  #  weight: 1
    
  - name: About
    url: /author/안수빈-ahn-soo-bin/
    weight: 100

  - name: AI
    url: /ai/
    weight: 200

  - parent: AI
    name: AI_Overview
    url: /ai/ai_info/
    weight: 210

  - parent: AI
    name: AI_Project 1
    url: /ai/ai_project1/
    weight: 220

  - parent: AI
    name: AI_Project 2
    url: /ai/ai_project2/
    weight: 230


  - name: Database
    url: /database/
    weight: 300

  - parent: Database
    name: DB_Project 1
    url: /database/db_project1/
    weight: 310


  - name: Python
    url: /python/
    weight: 400

  - parent: Python
    name: Py_Project 1
    url: /python/py_project1/
    weight: 410


  - name: Data Structure
    url: /ds/
    weight: 500

  - parent: Data Structure
    name: DS_Overview
    url: /ds/ds_info/
    weight: 510

  - parent: Data Structure
    name: DS_Project 1
    url: /ds/ds_project1/
    weight: 520

  - parent: Data Structure
    name: DS_Project 2
    url: /ds/ds_project2/
    weight: 530

  - parent: Data Structure
    name: DS_Project 3
    url: /ds/ds_project3/
    weight: 540


  - name: Skills
    url: /my-skills/
    weight: 600

  - name: Contact
    url: /contact/
    weight: 700
